# Site settings
title: syncopated studios
description: >
  Artful experiences and experiments in the pursuit of optimal enjoyment

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://syncopatedstudios.github.io" # the base hostname & protocol for your site

author:
  fullname: Bob
  googleplus:
  github: b08x
  twitter:
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html", "Gemfile", "Gemfile.lock", "resources/*", "_drafts/*", "_mdwriter.cson"]

# Build settings
highlighter: null
markdown: kramdown

plugins:
  - jekyll-assets
  # - jekyll-transform

assets:
  compress:
    css: sass
    js: uglifier

  cache: false

  sources:
    - assets/img
    - assets/vendor

  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]

# transform:
#   folder: '_wiki'
#   page_yaml:
#     layout: page
#   post_yaml:
#     layout: page
